version: '3.9'

services:
  app_pup:
    image: alexanderkatzur1628/pickup-point:v1
    ports:
      - "8080:8080"
    depends_on:
      - db_pup
    environment:
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
  db_pup:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_DB=db_pickup
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
