name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  push_compose:
    name: Push docker_compose.yml to remote server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Copy docker-compose.yml to server
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.REMOTE_USER}}
          key: ${{secrets.PRIVATE_KEY}}
          port: 22
          source: "docker-compose.yml"
          target: "/home/${{secrets.REMOTE_USER}}/pick_up/"

  build_and_push_images:
    name: Push image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME}}
          password: ${{ secrets.DOCKERHUB_PASSWORD}}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push to DockerHub
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          push: true
          tags: alexanderkatzur1628/pickup-point:v1

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build_and_push_images, push_compose]
    steps:
      - name: Connect with SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.REMOTE_USER}}
          key: ${{secrets.PRIVATE_KEY}}
          script: |
            cd /home/${{secrets.REMOTE_USER}}/pick_up/
            chmod 777 .env
            echo DB_USER=${{ secrets.DB_USER}} >> .env
            echo DB_PASSWORD=${{ secrets.DB_PASSWORD}} >> .env
            
            sudo -S docker stop alexanderkatzur1628/pickup-point:v1
            sudo -S docker rm alexanderkatzur1628/pickup-point:v1
            sudo -S docker rmi alexanderkatzur1628/pickup-point:v1
            sudo -S docker-compose -f /home/${{secrets.REMOTE_USER}}/pick_up/docker-compose.yml pull
            sudo -S docker-compose -f /home/${{secrets.REMOTE_USER}}/pick_up/docker-compose.yml up -d --remove-orphans
            sudo -S docker system prune -f
            sudo -S docker ps -a